[build]
  base    = "frontend"
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL         = "https://spice-shop-backend.onrender.com"
  NEXT_PUBLIC_WHATSAPP_NUMBER = "919999999999"
  NEXT_PUBLIC_ENABLE_RAZORPAY = "false"
